---

- name: installing unzip
  apt:
    name: unzip

- name: Create Consul Group
  group:
    name: '{{consul_group}}'
    state: present

- name: Creating Consul User
  user:
    name: '{{consul_user}}'
    group: '{{consul_group}}'
    shell: /bin/false
    state: present
    
- name: Create Directories
  file:
    path: '{{item.d}}'
    state: directory
    recurse : yes
    owner: '{{consul_user}}'
    group: '{{consul_group}}'
    mode: '{{item.m}}'
  with_items:
    - d: '{{consul_data_dir}}'
      m: '0755'
    - d: '{{consul_agent_dir}}'
      m: '0755'

- name: Download Consul Zip
  get_url:
    url: "{{consul_download_url}}"
    dest: "/opt"

- name: Unzip Downloaded Zip
  unarchive:
    src: "/opt/{{ consul_version }}"
    dest: "{{consul_bin_path}}"
    owner: '{{consul_user}}'
    group: '{{consul_group}}'
    remote_src: yes
    creates: "{{consul_bin_path}}/consul"

- name: Create Consul agent
  template:
    src: consul_agent.json.j2
    dest: "{{consul_agent_dir}}/{{inventory_hostname_short}}.json"
    mode: 0755
  notify:
    - Restart Consul

- name: Create Consul systemd service file
  template:
    src: consul.service.j2
    dest: "/etc/systemd/system/consul.service"
    mode: 0644
  notify:
    - Daemon Reload 
    - Restart Consul

- name: Cleanup
  file:
    path: "/opt/{{ consul_version }}"
    state: absent
